####################################
####### START OF SIMULATION ########

library(nimble, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)

### DEFINING SEED FOR SIMULATIONS

set.seed(20)

###### MODEL STRUCTURE FOR SIMULATION ######

simulationCode <- nimbleCode({
  for (i in 1:npatients) {
    for (j in 1:nvisit) {
      logit(prob[i,j]) <- beta01 + inprod(beta1[1:p], x[i, 1:p]) + b[i] # True occupancy status
      logit(prob2[i,j]) <- beta02 + inprod(beta2[1:p], x[i, 1:p]) + b[i] # True occupancy status
      
      y1[i,j] ~ dbern(prob[i,j]) # Observed data
      y2[i,j] ~ dbern(prob2[i,j]) # Observed data
    }
  }
  
})

### NUMBER OF COVARIATES

p <- 3                                                          

### COVARIATE MATRIX DEFINITION

X <- matrix(c(c(rep(0,30), rep(1,30), rep(0,60)),
              c(rep(0,60), rep(1,30), rep(0,30)),
              c(rep(0,90), rep(1,30))), nrow = 120, ncol = 3)   

### DEFINITION OF SHARED RANDOM EFFECT

B <- c()

B[1:15] <- rnorm(15, 3, sd = 0.1)
B[16:30] <- rnorm(15, -1, sd = 0.1)
B[31:45] <- rnorm(15, 1, sd = 0.1)
B[46:60] <- rnorm(15, 1, sd = 0.1)
B[61:65] <- rnorm(5, 2, sd = 0.1)
B[66:90] <- rnorm(25, 0, sd = 0.1)
B[91:105] <- rnorm(15, -1, sd = 0.1)
B[106:120] <- rnorm(15, 3, sd = 0.1)

###### BUILDING MODEL FOR SIMULATION ######
###
### "npatients" = number of patients; "nvisit" = number of longitudinal measures
### "b" = shared random effect; "x" = Covariate matrix

simModel <- nimbleModel(code = simulationCode,
                        constants = list(npatients = 120, nvisit = 21, p = p,
                                         x = X,
                                         beta01 = 1, beta1 = rnorm(p, 0, 1),
                                         beta02 = -1, beta2 = rnorm(p, 0, 1),
                                         b = B)
                        ) 

### CHECKING IF RESPONSE DON'T EXIST: Na's

simModel$calculate('y1')
simModel$calculate('y2')

### COMPILE MODEL

CsimModel <- compileNimble(simModel)

### GETTING THE NODES NECESSARY TO SIMULATE THE RESPONSE VARIABLES

prob_list <- c()
prob2_list <- c()
for (i in 1:21) {
  prob_list <- c(prob_list, sprintf(sprintf("prob[%%d, %d]", 1:21)[i], 1:120))
  prob2_list <- c(prob2_list, sprintf(sprintf("prob2[%%d, %d]", 1:21)[i], 1:120)) 
}

nodesToSim <- CsimModel$getDependencies(c(prob_list, prob2_list),
                                        self = F, downstream = T)

### SIMULATING THE RESPONSE VARIABLES

CsimModel$simulate(nodesToSim)

### CHECKING BETA'S COEFFICIENTS GENERATED BY THE SEED

CsimModel$beta1
CsimModel$beta2

### CHECKING THE RESPONSE VARIABLES

CsimModel$y1
CsimModel$y2

### DEFINING AUXILIARY VARIABLE TO SAVE RESPONSE VARIABLES
### TO USE IN THE "Teste.R" files

simulatedY1s <- CsimModel$y1

simulatedY2s <- CsimModel$y2

simulatedY1s

simulatedY2s

####### END OF SIMULATION ########
##################################